name: Koopy
description: App for creating shopping lists.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flare_flutter: ^2.0.6
  password_strength: ^0.1.2
  simple_animations: ^2.3.1
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1
  http: ^0.12.2

  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Koopy"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/logo.png"
  image_path_android: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/animations/splashscreen.flr