name: Koopy
description: App for creating shopping lists.

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flare_flutter: ^2.0.6
  password_strength: ^0.1.2
  simple_animations: ^2.3.1
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1
  http: ^0.12.2
  intl: ^0.16.1
  circular_check_box: ^1.0.4
  shared_preferences: ^0.5.12+4
  numberpicker: ^1.3.0

  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Koopy"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/logo.png"
  image_path_android: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/animations/
  fonts:
    - family: "Nunito"
      fonts:
        - asset: "assets/fonts/Nunito-Black.ttf"
          weight: 900
        - asset: "assets/fonts/Nunito-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Nunito-Regular.ttf"
          weight: 500
        - asset: "assets/fonts/Nunito-Light.ttf"
          weight: 300
